[workspace]
members = ["crates/*"]
resolver = "2"

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2

[profile.release]
debug = true
