[workspace]
members = ["crates/*"]

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release]
debug = true